config/routes.rb
Rails.application.routes.draw do
  
  root to: 'static_pages#home'
  get  '/signup',  to: 'users#new'
  # post '/signup',  to: 'users#create'

  resources :users

  	get '/login', to: "sessions#new"
	post '/login', to: "sessions#create"
	delete '/logout', to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	
  before_save { email.downcase! }
	validates :first_name, presence: true
	validates :last_name, presence: true
	  
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 50 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 10 }

    # Returns the hash digest of the given string.
 
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Email ou mot de passe invalide'
      render 'new'
    end
  end 

  def destroy
    log_out #if logged_in?
    redirect_to root_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	# @users = User.all
    if current_user
      @users = User.all
    else 
      flash[:warning] = "Inscris-toi"
      redirect_to login_path
    end 
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	
    if @user.save
      log_in @user
      flash[:success] = "Bienvenu au club"
      redirect_to @user
    else
      render 'new'
    end

  end 

  def show
  	# @user = User.find(params[:id])
    if current_user == User.find(params[:id])
      @user = current_user
    else 
      flash[:warning] = "Erreur"
      redirect_to root_path
    end 
  end

  def edit
  	# @user = User.find(params[:id])
    if current_user == User.find(params[:id])
      @user = current_user
    else 
      flash[:warning] = "Erreur"
      redirect_to root_path
    end 
  end

  def update
  	@user = User.find(params[:id])
  	@user = User.update(user_params)
  	redirect_to users_path
  end 

  def destroy
  	@user = User.find(params[:id])
  	@user.destroy
  	redirect_to users_path
  end 


  private

  def user_params
  	params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end


  def current_user
  	if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end 

    # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    # forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end



end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar for the given user.
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Club app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Utilisateurs", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profil", current_user %></li>
              <li><%= link_to "Paramètres", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Deconnexion", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Connexion", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Club Privé</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap, via les CDNs, -->
 <!--    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->
    
  </head>
  <body>
    <%= render 'layouts/header' %>

    <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
            
          <%= debug(params) if Rails.env.development? %>
    </div>
    
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Le formulaire est invalide <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Bienvenu au club privé</h1>

  <h2>
    C'est un club privé, connecte toi ou inscrit toi
  </h2>

  <%= link_to "S'inscrire", "/signup", class: "btn btn-lg btn-primary" %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<h1>Edit</h1>

<!-- Helper form_for-->
	<%= form_for @user do |f| %>

		<%= render 'shared/error_messages' %>
		<div class="form-group">
			<%= f.label :first_name %>  <!-- , class: "sr-only"", -->
			<%= f.text_field :first_name, class: "form-control", placeholder:"Ton prénom"%>
		</div>
		<div class="form-group">
			<%= f.label :last_name %>  <!-- , class: "sr-only"", -->
			<%= f.text_field :last_name, class: "form-control", placeholder:"Ton nom"%>
		</div>		
		<div class="form-group">	
			<%= f.label :email%>
			<%= f.email_field :email, class: "form-control", placeholder: "ton.email@example.com" %>		<!-- f.email_field ; type: "email", -->
		</div>
		<div class="form-group">
			<%= f.label :password, "Min. 10 characters"%>
			<%= f.text_field :password, class: "form-control", placeholder: "Mot de passe" %>	<!-- f.password_field ; type: "password",-->
		</div>
		<div class="form-group">
			<%= f.label :password_confirmation, "Confirmation" %>
	      	<%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirmer mot de passe" %>
      	</div>
		<div class="actions"> 
			<%= f.submit "Edit", class: "btn btn-primary" %>
		</div>
	<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<% @users.each.with_index do |user,ind| %>
	<div class="card">
    	<div class="card-body">
        	<h5 class="card-title">
        		User: <%= user.first_name %> <%= user.last_name %>
        	</h5>
        	<h6 class="card-subtitle mb-2 text-muted">
        		Email: <%= user.email %>
        	</h6>
          	<a href= <%= user_path(user.id) %> class ="card-link">More...</a>
    	</div>
	</div>
<% end %>  

app/views/users/new.html.erb
<% provide(:title, "Inscription") %>
<h1>Sign Up</h1>

<!-- Helper form_for-->
	<%= form_for @user do |f| %>

		<%= render 'shared/error_messages' %>
		<div class="form-group">
			<%= f.label :first_name %>  <!-- , class: "sr-only"", -->
			<%= f.text_field :first_name, class: "form-control", placeholder:"Ton prénom"%>
		</div>
		<div class="form-group">
			<%= f.label :last_name %>  <!-- , class: "sr-only"", -->
			<%= f.text_field :last_name, class: "form-control", placeholder:"Ton nom"%>
		</div>		
		<div class="form-group">	
			<%= f.label :email%>
			<%= f.email_field :email, class: "form-control", placeholder: "ton.email@example.com" %>		<!-- f.email_field ; type: "email", -->
		</div>
		<div class="form-group">
			<%= f.label :password, "Min. 10 characters"%>
			<%= f.password_field :password, class: "form-control", placeholder: "Mot de passe" %>	<!-- f.password_field ; type: "password",-->
		</div>
		<div class="form-group">
			<%= f.label :password_confirmation, "Confirmation" %>
	      	<%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirmer mot de passe" %>
      	</div>
		<div class="actions"> 
			<%= f.submit "Create", class: "btn btn-primary" %>
		</div>
	<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.first_name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
		<h1>
		  <%= @user.first_name %>
		</h1>
    </section>
  </aside>
</div>

<div class="card">
  <div class="card-header">
    User: <%= @user.first_name %>
  </div>
  <div class="card-body">
    <h5 class="card-title">Email: <%= @user.email %></h5>
    <p class="card-text">Utilisateur.</p>
    <a href= <%= edit_user_path(@user.id) %> class="btn btn-info">
    	Edit
    </a>
    <%= link_to 'Clique pour détruire', @user, method: :delete, class:"btn btn-danger" %>
  </div>
</div>